name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate the snake
        uses: Platane/snk@master
        with:
          github_user_name: shivam-attri-85
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push generated files
        run: |
          if [ -d "dist" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add dist
            git commit -m "Generate Snake Animation" || echo "No changes to commit"
            git push
          fi
